from tkinter import*

root = Tk()
root.resizable(0,0)
root.title("my calculator")
root.geometry("250x400+300+300")
data=StringVar()
lbl=Label(root,text="label",
          anchor=SE,textvariable=data)
lbl.pack(expand=TRUE,fill="both")

btnrow1=Frame(root)
btnrow1.pack(expand=TRUE)

btnrow2=Frame(root)
btnrow2.pack(expand=TRUE)

btnrow3=Frame(root)
btnrow3.pack(expand=TRUE)

btnrow4=Frame(root)
btnrow4.pack(expand=TRUE)

btn1 = Button(btnrow1, text="1",font=("verdana",30),border=0)
btn2= Button(btnrow1, text="2",font=("verdana",30),border=0)
btn3 = Button(btnrow1, text="3",font=("verdana",30),border=0)
btn4=Button(btnrow1,text="+",font=("verdana",30),border=0)
btn1.pack(expand=TRUE,fill="both",side=LEFT)
btn2.pack(expand=TRUE,fill="both",side=LEFT)
btn3.pack(expand=TRUE,fill="both",side=LEFT)
btn4.pack(expand=TRUE,fill="both",side=LEFT)
btn1 = Button(btnrow2, text="4",font=("verdana",30),border=0)
btn2= Button(btnrow2, text="5",font=("verdana",30),border=0)
btn3 = Button(btnrow2, text="6",font=("verdana",30),border=0)
btn4=Button(btnrow2,text="-",font=("verdana",30),border=0)
btn1.pack(expand=TRUE,fill="both",side=LEFT)
btn2.pack(expand=TRUE,fill="both",side=LEFT)
btn3.pack(expand=TRUE,fill="both",side=LEFT)
btn4.pack(expand=TRUE,fill="both",side=LEFT)
btn1 = Button(btnrow3, text="7", font=("verdana", 30),border=0)
btn2 = Button(btnrow3, text="8", font=("verdana", 30),border=0)
btn3 = Button(btnrow3, text="9", font=("verdana", 30),border=0)
btn4 = Button(btnrow3, text="*", font=("verdana", 30),border=0)
btn1.pack(expand=TRUE, fill="both", side=LEFT)
btn2.pack(expand=TRUE, fill="both", side=LEFT)
btn3.pack(expand=TRUE, fill="both", side=LEFT)
btn4.pack(expand=TRUE, fill="both", side=LEFT)
btn1 = Button(btnrow4, text="C",font=("verdana",30),border=0,relief=GROOVE)
btn2= Button(btnrow4, text="0",font=("verdana",30),border=0,relief=GROOVE)
btn3 = Button(btnrow4, text="=",font=("verdana",30),border=0,relief=GROOVE)
btn4=Button(btnrow4,text="/",font=("verdana",30),border=0,relief=GROOVE)
btn1.pack(expand=TRUE,fill="both",side=LEFT)
btn2.pack(expand=TRUE,fill="both",side=LEFT)
btn3.pack(expand=TRUE,fill="both",side=LEFT)
btn4.pack(expand=TRUE,fill="both",side=LEFT)
root.mainloop()